### ISSUE TITLE
Package not in PyPi

### ISSUE THREAD

**Issue by coisnepe** [PrefectHQ/prefect-hightouch#3]
Hello,
Contrary to what's suggested in the Readme, it looks like this package is [not in PyPi](https://pypi.org/search/?q=prefect-hightouch&o=). Is it still being developed? Do you have plans to release it? And until it's released, can the V1 tasks be used as a substitute?
Thanks!

Edit: Turns out this package is just a boilerplate… A "disclaimer" somewhere to highlight that it's not useable yet would be useful!

**Comment by ahuang11** [comment]
Hi @coisnepe. Thanks for submitting the issue and sorry I missed this! Yes, this package is still in development, but will be available in the near future.

**Comment by ahuang11** [comment]
`prefect-hightouch` is now available on pypi!

**Comment by ahuang11** [comment]
Actually the release pipeline was missing a pypi token cc: @desertaxle
