### ISSUE TITLE
Add `trigger_hightouch_sync` task

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-hightouch#8]
Create a task that triggers a Hightouch sync. The task should accept a `HightouchCredentials` block, a sync ID, and a flag to specify whether or not to do a full resync. The task should return the ID of the triggered sync run. 

Link to Hightouch API documentation for the route: https://hightouch.com/docs/api-reference#operation/TriggerRun

**Comment by ahuang11** [comment]
I am also going to include https://hightouch.com/docs/api-reference#operation/TriggerRunCustom because I think slugs are easier to remember and use without looking up the ID.
